db:
    postgres:
        host: timeline_db_dev
        port: 5432
        user: root
        password: '1234'
        database: time_line
sentry:
    dsn: 'https://732f939c0e7b44358fcbc910b22ae7d6@o4503963017609216.ingest.sentry.io/4503963023572992'
    traceSampleRate: 0.0
    maxBreadcrumbs: 50
    sendDefaultPii: '1' # '0' - false, '1' - true
rabbitmq:
    queueName: resource-queue
    host: rabbitmq
    port: 5672
    user: admin
    password: admin
hrm:
    syncApi: https://casdoor.tetcha.site/api/get-users?owner=tpp
    token:
        name: Authorization
        value: Bearer eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IlN5bmNocm9uaXphdGlvbmkiLCJleHAiOjE2NjYxNjY4MjAsImlhdCI6MTY2NjE2NjgyMH0.ncebjE5oRxiws6-FakNo7tgM9HRCJA3B10s6oPAzXW8
resourceSync:
    messageLength: 10
